USE [master]
GO

/****** Object:  Database [JobFinder]    Script Date: 10/13/2023 7:10:50 PM ******/
CREATE DATABASE [JobFinder]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JobFinder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobFinder.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JobFinder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\JobFinder_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JobFinder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [JobFinder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [JobFinder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [JobFinder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [JobFinder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [JobFinder] SET ARITHABORT OFF 
GO

ALTER DATABASE [JobFinder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [JobFinder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [JobFinder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [JobFinder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [JobFinder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [JobFinder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [JobFinder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [JobFinder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [JobFinder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [JobFinder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [JobFinder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [JobFinder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [JobFinder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [JobFinder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [JobFinder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [JobFinder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [JobFinder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [JobFinder] SET RECOVERY FULL 
GO

ALTER DATABASE [JobFinder] SET  MULTI_USER 
GO

ALTER DATABASE [JobFinder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [JobFinder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [JobFinder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [JobFinder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [JobFinder] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [JobFinder] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [JobFinder] SET QUERY_STORE = OFF
GO

ALTER DATABASE [JobFinder] SET  READ_WRITE 
GO

